### PR TITLE
chore: added commitlint support

### PR DESCRIPTION
**Pull request by christyjacob4**
## What does this change do and why
This PR adds Commit lint support to the repo ensuring that contributors follow commit message conventions

You can see it in action here

Screenshot 2020-10-01 at 11 01 16 PM

### CODE REVIEW

**Comment by christyjacob4** [comment]
I see that npm is using an internal intuit registry to fetch packages? 
```
error An unexpected error occurred: "https://registry.npmjs.intuit.com:443/artifactory/api/npm/npm-intuit/@commitlint/load/-/load-11.0.0.tgz: Request failed \"403 Forbidden\"".
```

**Comment by Aghassi** [comment]
Not intended, feel free to regen the lockfile or use a see script to replace strings matching that with yarn pkg registry. Sanitizing isn't always easy unfortunately. Cc @hipstersmoothie @krohrsb

**Comment by christyjacob4** [comment]
Okay got it. Let me fix that

**Review by Aghassi — APPROVED** [review]

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v6.5.4`](https://github.com/intuit/commently/releases/tag/v6.5.4) :rocket:

**Pull request merged**
